[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas>=1.3.5",
    "numpy>=1.21.5",
    "Pillow>=8.4.0",
    "openpyxl>=3.0.9",
    "matplotlib>=3.5.1"
]
build-backend = "setuptools.build_meta"